name: build image
description: run build
inputs:
  IMAGE_NAME: 
    description: "image name"
    required: true

runs:
  using: composite
  steps:
    - name: Build Docker image
      id: build
      shell: bash
      run: |
        docker build -t ${{ inputs.IMAGE_NAME }} .

   