name: build image
description: run build
inputs:
  IMAGE_NAME: 
    description: "registry name"
    required: true

runs:
  using: composite 
  steps: 
    - name: Build Docker image
      shell: bash
      run: |
        docker build -t ${{ inputs.IMAGE_NAME }} .

   