name: publish image
description: run container image en push it to the registry
inputs:
  registry: 
    description: "registry name"
    required: true
  username:
    description: "user name"  
    required: true
  password:
    description: "token action"  
    required: true
  CONTAINER_NAME: 
    description: "name of container"  
    required: true
  IMAGE_NAME: 
    description: "name of the image"  
    required: true

runs:
  using: composite
  steps:
    - name: "Log in to the Container registry"
      uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
      with:
        registry: ${{ inputs.registry }}
        username: ${{ inputs.username }}
        password: ${{ inputs.password }}

    - name: Run container
      shell: bash
      run: |
        docker version
        docker images
        docker run --name ${{ inputs.CONTAINER_NAME }} -d -p 8080:80 ${{ inputs.IMAGE_NAME }}
        sleep 5
        docker ps
        apk update && apk --no-cache add curl curl-dev bash
        curl "http://localhost:8080"
    
    - name: Delete container
      shell: bash
      run: |
        docker stop ${{ inputs.CONTAINER_NAME }}
        docker rm -f ${{ inputs.CONTAINER_NAME }}