name: copy files
on: 
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "Main.java"
        target: "appfiles/main.java"
    - name: run tests
      run: |
        cd "appfiles"
        ls
        cat main.java
    - name: Retrieve secret
      env:
        super_secret: ${{ secrets.SUPERSECRET }}
        user_secret: ${{ secrets.GITHUB_USER }}
      run: |
        echo $super_secret
        echo $user_secret
        echo ${{github.event_name}}
        echo "ref name :" ${{github.ref_name}}
        echo "sha :" ${{github.sha}}
        echo $GITHUB_SERVER_URL

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node
      with:
        path: ./
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Dockerfile') }}
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-