name: Enforce PR checklist
on: 
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      output1: ${{ steps.checkboxes.outputs.success }}
    env:
        GH_TOKEN: ${{ secrets.TOCKEN_REGISTRY }}
        A: ${{ toJson(github.event.pull_request) }}
        B: ${{ github.event.pull_request.id }}
        C: ${{ github.event.pull_request.number }}
        D: ${{ github.event.pull_request.state }}
        E: ${{ github.event.pull_request.title }}
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "Main.java"
        target: "appfiles/main.java"
    - name: run tests
      run: |
        cd "appfiles"
        ls
        cat main.java
    - name: Retrieve secret
      env:
        super_secret: ${{ secrets.SUPERSECRET }}
        user_secret: ${{ secrets.GITHUB_USER }}
        GH_TOKEN: ${{ secrets.TOCKEN_REGISTRY }}
      run: |
        echo $super_secret
        echo $user_secret
        echo ${{github.event_name}}
        echo "ref name :" ${{github.ref_name}}
        echo "sha :" ${{github.sha}}
        echo "repository : " ${{github.repository}}
        echo $GITHUB_BASE_REF
      
    # Ajoutez un fichier README.md au dépôt
    - name: Add README.md
      run: |
        echo "# Bienvenue dans ce projet" > README.md
        echo "Ce fichier a été ajouté automatiquement via une GitHub Action." >> README.md    
    
    # - name: Validate PR checkboxes
    #   id: checkboxes
    #   env:
    #     GITHUB_TOKEN: ${{ secrets.TOCKEN_REGISTRY }}
    #   run: |
    #     PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q '.body')
    #     if echo "$PR_BODY" | grep -q '\- \[ \]'; then
    #       echo "❌ Certaines cases ne sont pas cochées dans la checklist."
    #       echo "success=false" >> $GITHUB_OUTPUT
    #       exit 1
    #     else
    #       echo "✅ All required checkboxes are checked!"
    #       echo "success=true" >> $GITHUB_OUTPUT
    #     fi
          


        # EXPECTED_SHA=${{ github.event.pull_request.head.sha }}
        # if ! echo "$PR_BODY" | grep -q "$EXPECTED_SHA"; then
        #   echo "❌ Le SHA dans la PR ne correspond pas au SHA actuel (${EXPECTED_SHA})."
        #   exit 1
        # fi
        


        # if grep -q '\- \[ \]' "$GITHUB_EVENT_PATH"; then
        #   echo "Error: Not all ❌ checklist items are completed."
        #   exit 1
        # else
        #   echo "✅ All required checkboxes are checked!"
        # fi

        # PR_BODY=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }})
        
        # CHECKLIST=$(echo "$PR_BODY" | jq -r '.body' | grep -P "^\s*- \[ \]") #Look for unchecked boxes
        # if [ ! -z "$CHECKLIST" ]; then
        #   echo "Error: Not all ❌ checklist items are completed."
        #   exit 1
        # else
        #   echo "✅ All required checkboxes are checked!"
        # fi


        # Define the required checkbox text
        # REQUIRED_CHECKBOXES=("Task 1" "Task 2")
        # Check for each required checkbox
        # for TASK in "${REQUIRED_CHECKBOXES[@]}"; do
        #   if ! echo "$PR_BODY" | grep -qE "- \[x\] $TASK"; then
        #     echo "❌ Checkbox for '$TASK' is not checked!"
        #     exit 1
        #   fi
        # done
    
    - name: Installer jq sans sudo
      run: |
        JQ_VERSION="1.6"
        JQ_BINARY="jq-linux64"
        curl -L -o jq "https://github.com/stedolan/jq/releases/download/jq-${JQ_VERSION}/${JQ_BINARY}"
        chmod +x jq
        mkdir -p $HOME/bin
        mv jq $HOME/bin/
        echo "$HOME/bin" >> $GITHUB_PATH
    - name: Valider les cases cochées dans la description de la PR
      id: validate
      env: 
        GITHUB_EVENT_PATH: ${{ github.event_path }}
        
      run: |
        PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
        
        echo $PR_BODY
        if echo "$PR_BODY" | grep -q '\- \[x\] Mon code'; then
          echo "✅ All required checkboxes are checked!" 
        else
          echo "Erreur : Certaines cases de la checklist ne sont pas cochées."
          exit 1 
        fi
        
    - name: Valider la description de la PR
      env:
        GITHUB_EVENT_PATH: ${{ github.event_path }}
      run: |
        PR_BODY=$(jq -r '.pull_request.body' "$GITHUB_EVENT_PATH")
        if [[ "$PR_BODY" == *"Empty"* ]]; then
          echo "The text 'Empty' exists in the PR body."
          
        else
          echo "The text 'Empty file' does not exist in the PR body."
          
        fi

    - name: Generate 0 or 1
      id: generate_number
      run: echo "random_number=$(($RANDOM % 2))" >> $GITHUB_OUTPUT
    - name: Pass or fail
      run: |
        if [[ ${{ steps.generate_number.outputs.random_number }} == 0 ]]; then 
          exit 0; 
        else 
          exit 1; 
        fi
    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node
      with:
        path: ./
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Dockerfile') }}
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-

  notify:
    needs: build
    if: always()  # S'exécute même si la validation échoue
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Send notification to PR
      env:
        GITHUB_TOKEN: ${{ secrets.TOCKEN_REGISTRY }}
      run: |
        echo ${{ needs.build.outputs.output1 }}
        if [ "${{ needs.build.outputs.output1 }}" == "false" ]; then
          echo "Error: Not all ❌ checklist items are completed."
          COMMENT_BODY="Not all ❌ checklist items are completed."
        else
          echo "✅ All required checkboxes are checked!"
          COMMENT_BODY="✅ All required checkboxes are checked!"
        fi
        gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT_BODY"