name: Enforce PR checklist
on: 
  pull_request:
    types: [opened, edited, reopened, synchronize]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    env:
        GH_TOKEN: ${{ secrets.TOCKEN_REGISTRY }}
        A: ${{ toJson(github.event.pull_request) }}
        B: ${{ github.event.pull_request.id }}
        C: ${{ github.event.pull_request.number }}
        D: ${{ github.event.pull_request.state }}
        E: ${{ github.event.pull_request.title }}
    steps:
    - uses: actions/checkout@master
    - name: copy file
      uses: canastro/copy-file-action@master
      with:
        source: "Main.java"
        target: "appfiles/main.java"
    - name: run tests
      run: |
        cd "appfiles"
        ls
        cat main.java
    - name: Retrieve secret
      env:
        super_secret: ${{ secrets.SUPERSECRET }}
        user_secret: ${{ secrets.GITHUB_USER }}
        GH_TOKEN: ${{ secrets.TOCKEN_REGISTRY }}
      run: |
        echo $super_secret
        echo $user_secret
        echo ${{github.event_name}}
        echo "ref name :" ${{github.ref_name}}
        echo "sha :" ${{github.sha}}
        echo "repository : " ${{github.repository}}
        echo $GITHUB_BASE_REF
      
    # Ajoutez un fichier README.md au dépôt
    - name: Add README.md
      run: |
        echo "# Bienvenue dans ce projet" > README.md
        echo "Ce fichier a été ajouté automatiquement via une GitHub Action." >> README.md    
    
    - name: Validate PR checkboxes
      id: checkboxes
      env:
        GITHUB_TOKEN: ${{ secrets.TOCKEN_REGISTRY }}
      run: |
        # Get the PR body

        # if grep -q '\- \[ \]' "$GITHUB_EVENT_PATH"; then
        #   echo "Error: Not all ❌ checklist items are completed."
        #   exit 1
        # else
        #   echo "✅ All required checkboxes are checked!"
        # fi

        # PR_BODY=$(curl -s https://api.github.com/repos/${{ github.repository }}/issues/${{ github.event.pull_request.number }})
        
        CHECKLIST=$(grep -P "^\s*- \[ \]" "$GITHUB_EVENT_PATH") #Look for unchecked boxes
        if [ ! -z "$CHECKLIST" ]; then
          echo "Error: Not all ❌ checklist items are completed."
          exit 1
        else
          echo "✅ All required checkboxes are checked!"
        fi
        
        # Define the required checkbox text
        # REQUIRED_CHECKBOXES=("Task 1" "Task 2")

        # Check for each required checkbox
        # for TASK in "${REQUIRED_CHECKBOXES[@]}"; do
        #   if ! echo "$PR_BODY" | grep -qE "- \[x\] $TASK"; then
        #     echo "❌ Checkbox for '$TASK' is not checked!"
        #     exit 1
        #   fi
        # done

    - name: Cache node modules
      uses: actions/cache@v3
      env:
        cache-name: cache-node
      with:
        path: ./
        key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Dockerfile') }}
        restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-