on:
  push:
    branches:
    - develop

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: pwd
        run: |
          pwd
          ls -a
          ls .github/
      - name: Hello world action step

        uses: .github/actions/firstaction
        id: hello
        with:
          who-to-greet: 'Michel'
      # Use the output from the `hello` step
      - name: Get the output time
        run: echo "The time was ${{ steps.hello.outputs.time }}"
