
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches:
    - release2

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    outputs:
      outputtag: ${{ steps.meta.outputs.tags }}
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4
      
      
      - name: Use local build_image_action
        uses: ./.github/actions/build_image
        with:
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
      

      - name: Use local run_image_action
        uses: ./.github/actions/run_and_test_image 
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOCKEN_REGISTRY }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }} 
      
      - name: Use local push_image_to_registry
        uses: ./.github/actions/push_image_to_registry 
        with:
          TAG: $GITHUB_RUN_NUMBER
          REPOSITORY_NAME: ${{ github.repository }}
          REGISTRY: ${{ secrets.REGISTRY }}
          IMAGE_NAME: ${{ secrets.IMAGE_NAME }}
           
