
name: Create and publish a Docker image

# Configures this workflow to run every time a change is pushed to the branch called `release`.
on:
  push:
    branches:
    - release2

# There is a single job in this workflow. It's configured to run on the latest available version of Ubuntu.
jobs:
  build-and-push-image:
    runs-on: ubuntu-20.04
    steps:
      - name: "Checkout repository"
        uses: actions/checkout@v4

      - name: Use local build_image_action
        uses: ./.github/actions/build_image
        # with:
        #   REGISTRY: ${{ secrets.REGISTRY }}
        #   REPOSITORY_NAME: ${{ github.repository }}
      # This step uses [docker/metadata-action](https://github.com/docker/metadata-action#about) to extract tags and labels that will be applied to the specified image. The `id` "meta" allows the output of this step to be referenced in a subsequent step. The `images` value provides the base name for the tags and labels.
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ inputs.REGISTRY }}/${{ inputs.REPOSITORY_NAME }}

      - name: Use local run_image_action
        uses: ./.github/actions/run_and_test_image 
        with:
          registry: ${{ secrets.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.TOCKEN_REGISTRY }}
          CONTAINER_NAME: ${{ secrets.CONTAINER_NAME }}
          IMAGE_NAME: ${{ steps.meta.outputs.tags }} 
      
      - name: Use local push_image_to_registry
        uses: ./.github/actions/push_image_to_registry 
        with:
          TAG: $GITHUB_RUN_NUMBER
          REPOSITORY_NAME: ${{ github.repository }}
          REGISTRY: ${{ secrets.REGISTRY }}
           
