name: Vulnerability Scan

on:
  push:
    branches:
    - releaseed

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull nginx

      - uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: nginx
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'