name: Vulnerability Scan

on:
  push:
    branches:
    - release

jobs:
  scan:
    name: Daily Vulnerability Scan
    runs-on: ubuntu-latest
    steps:
      - name: Pull docker image
        run: docker pull nginx

      - uses: dataswift/gha-trivy@v3.0.0
        with:
          token: ${{ secrets.TOCKEN_REGISTRY }}
          image: nginx