name: Reusable workflow example

on:
  workflow_call:
    inputs:
      who-to-greet:  # id of input
        required: true
        type: string
        default: 'World'
    outputs:
      datato: # id of output
        description: 'The time we greeted you'

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.token }}
        configuration-path: ${{ inputs.config-path }}
