name: Reusable workflow example

on:
  workflow_call:
    inputs:
      who-to-greet:  # id of input
        required: true
        type: string
        default: 'World'
jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
      - name: Get the output time
        run: echo "The time was ${{ inputs.who-to-greet }}"


