name: Reusable workflow example

on:
  workflow_call:
    inputs:
      who-to-greet:  # id of input
        required: true
        type: string
        default: 'World'
    secrets:
      token:
        required: true

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v4
      with:
        repo-token: ${{ secrets.token }}
        configuration: ${{ inputs.who-to-greet }}
